blueprint:
  name: ZHA – IKEA STYRBAR (4-button) Remote for Lights
  description: >
    Control lights using an IKEA STYRBAR / Remote Control N2 (E2001/E2002)
    via ZHA. Supports on/off, smooth dimming, and custom left/right button
    actions (short + long press).
  domain: automation
  source_url: https://community.home-assistant.io/t/zha-ikea-four-button-remote-styrbar-for-lights-e2001-e2002/384482

  input:
    remote:
      name: Remote
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: Remote Control N2

    lights:
      name: Light(s)
      selector:
        target:
          entity:
            domain: light

    force_brightness:
      name: Force brightness on ON
      default: false
      selector:
        boolean:

    brightness:
      name: On brightness
      default: 50
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider

    hold_time:
      name: Hold repeat time
      default: 0.4
      selector:
        number:
          min: 0.1
          max: 1.5
          step: 0.1
          unit_of_measurement: seconds

    button_left_short:
      name: Left button – short press
      default: []
      selector:
        action:

    button_left_long:
      name: Left button – long press
      default: []
      selector:
        action:

    button_right_short:
      name: Right button – short press
      default: []
      selector:
        action:

    button_right_long:
      name: Right button – long press
      default: []
      selector:
        action:

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

variables:
  cmd: "{{ trigger.event.data.command }}"
  cluster: "{{ trigger.event.data.cluster_id }}"
  endpoint: "{{ trigger.event.data.endpoint_id }}"
  args: "{{ trigger.event.data.args }}"
  force_brightness: !input force_brightness

action:
  - choose:

      # ───── ON (top button short press)
      - conditions:
          - "{{ cmd == 'on' }}"
          - "{{ cluster == 6 }}"
          - "{{ endpoint == 1 }}"
        sequence:
          - choose:
              - conditions: "{{ force_brightness }}"
                sequence:
                  - service: light.turn_on
                    target: !input lights
            default:
              - service: light.turn_on
                target: !input lights

      # ───── OFF (bottom button short press)
      - conditions:
          - "{{ cmd == 'off' }}"
          - "{{ cluster == 6 }}"
          - "{{ endpoint == 1 }}"
        sequence:
          - service: light.turn_off
            target: !input lights

      # ───── BRIGHTEN (hold top button)
      - conditions:
          - "{{ cmd == 'move_with_on_off' }}"
          - "{{ cluster == 8 }}"
          - "{{ endpoint == 1 }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target: !input lights
                  data:
                    brightness_step_pct: 10
                    transition: !input hold_time
                - delay: !input hold_time

      # ───── DIM (hold bottom button)
      - conditions:
          - "{{ cmd == 'move' }}"
          - "{{ cluster == 8 }}"
          - "{{ endpoint == 1 }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target: !input lights
                  data:
                    brightness_step_pct: -10
                    transition: !input hold_time
                - delay: !input hold_time

      # ───── LEFT short
      - conditions:
          - "{{ cmd == 'press' }}"
          - "{{ cluster == 5 }}"
          - "{{ args == [257, 13, 0] }}"
        sequence: !input button_left_short

      # ───── LEFT long
      - conditions:
          - "{{ cmd == 'hold' }}"
          - "{{ cluster == 5 }}"
          - "{{ args == [3329, 0] }}"
        sequence: !input button_left_long

      # ───── RIGHT short
      - conditions:
          - "{{ cmd == 'press' }}"
          - "{{ cluster == 5 }}"
          - "{{ args == [256, 13, 0] }}"
        sequence: !input button_right_short

      # ───── RIGHT long
      - conditions:
          - "{{ cmd == 'hold' }}"
          - "{{ cluster == 5 }}"
          - "{{ args == [3328, 0] }}"
        sequence: !input button_right_long
