```yaml
blueprint:
  name: ZHA – IKEA STYRBAR (4-button) Remote for Lights (Split Toggle)
  description: >
    First ON press toggles the first light in the selection.
    Second ON press toggles all remaining lights.
    Based on IKEA STYRBAR / Remote Control N2 (E2001/E2002) using ZHA.
  domain: automation

  input:
    remote:
      name: Remote
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: Remote Control N2

    lights:
      name: Light(s)
      description: Select multiple lights. The first will be treated as "primary".
      selector:
        entity:
          domain: light
          multiple: true

    hold_time:
      name: Hold repeat time
      default: 0.4
      selector:
        number:
          min: 0.1
          max: 1.5
          step: 0.1
          unit_of_measurement: seconds

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

variables:
  cmd: "{{ trigger.event.data.command }}"
  cluster: "{{ trigger.event.data.cluster_id }}"
  endpoint: "{{ trigger.event.data.endpoint_id }}"
  lights_list: "{{ expand(lights) | map(attribute='entity_id') | list }}"
  primary_light: "{{ lights_list[0] if lights_list | length > 0 else none }}"
  secondary_lights: "{{ lights_list[1:] }}"

action:
  - choose:

      # ───── ON (top button short press)
      - conditions:
          - "{{ cmd == 'on' }}"
          - "{{ cluster == 6 }}"
          - "{{ endpoint == 1 }}"
        sequence:
          - choose:
              # If primary light is off → toggle it
              - conditions:
                  - "{{ primary_light is not none }}"
                  - "{{ is_state(primary_light, 'off') }}"
                sequence:
                  - service: light.toggle
                    target:
                      entity_id: "{{ primary_light }}"
            default:
              # Otherwise toggle all remaining lights
              - service: light.toggle
                target:
                  entity_id: "{{ secondary_lights }}"

      # ───── OFF (bottom button short press) → turn everything off
      - conditions:
          - "{{ cmd == 'off' }}"
          - "{{ cluster == 6 }}"
          - "{{ endpoint == 1 }}"
        sequence:
          - service: light.turn_off
            target: !input lights
            data:
              transition: 1

      # ───── BRIGHTEN (hold top button)
      - conditions:
          - "{{ cmd == 'move_with_on_off' }}"
          - "{{ cluster == 8 }}"
          - "{{ endpoint == 1 }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target: !input lights
                  data:
                    brightness_step_pct: 10
                    transition: !input hold_time
                - delay: !input hold_time

      # ───── DIM (hold bottom button)
      - conditions:
          - "{{ cmd == 'move' }}"
          - "{{ cluster == 8 }}"
          - "{{ endpoint == 1 }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target: !input lights
                  data:
                    brightness_step_pct: -10
                    transition: !input hold_time
                - delay: !input hold_time
```
